# Black Duck on GitHub-hosted ephemeral runner
name: blackduck

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  blackduck:
    runs-on: ubuntu-latest

    env:
      BLACKDUCK_URL: ${{ secrets.POLARIS_SERVER_URL }}
      BLACKDUCK_API_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
      PROJECT: chuckaude-hello-java
      BRANCH: ${GITHUB_REF##*/}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Black Duck Scan
      uses: blackducksoftware/github-action@v2
      with:
        args: --detect.project.name=hello-java --detect.project.version.name=main --detect.excluded.detector.types=GRADLE
    - name: Upload to CoPilot
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)
